@startuml
skinparam classAttributeIconSize 0

package network {
    interface Actions
    class ClientInterface
    class GameServer
    class PlayerClient
    class PlayerOnServer
    class MultiBoardViewController
    class MultiGameController
    class MultiplayerGame
    class JoinViewController
    class CreateViewController
    class OpponentBoard
}

package game {
    class Board
    class BoardListener
    class BoardPane
    class BoardViewController
    class GameController
    class GameoverViewController
    class Scores
    class StartViewController
    class Stone
    class StoneType
    class Stopwatch
}


SupertetrisApp ..> StartViewController : starts
StartViewController ..> BoardViewController : starts
StartViewController ..> JoinViewController : starts
StartViewController ..> CreateViewController : starts
BoardViewController "1" *--* "1" GameController
GameController "1" *-- "1" Board
GameController "1" *-- "1" Stopwatch
GameController "1" *-- "1" Scores
BoardListener <|-- Board
Board "1" *-- "*" Stone
Board *-- BoardPane
GameController <|-- MultiGameController
GameController *-- BoardPane
BoardViewController ..> GameoverViewController : starts
MultiBoardViewController ..> GameoverViewController : starts
MultiBoardViewController *-- MultiGameController
MultiGameController *-- OpponentBoard
MultiGameController  *-- BoardPane
MultiplayerGame ..> MultiBoardViewController : starts
OpponentBoard  *-- BoardPane

'ViewController <|-- StartViewController
'ViewController <|-- BoardViewController
'ViewController <|-- MultiBoardViewController
'ViewController <|-- JoinViewController
'ViewController <|-- CreateViewController
'ViewController <|-- GameoverViewController

JoinViewController *-- PlayerClient
JoinViewController *-- ClientInterface
JoinViewController *-- MultiplayerGame
MultiBoardViewController *-- MultiplayerGame
MultiGameController *-- ClientInterface
CreateViewController *-- PlayerClient
CreateViewController *-- ClientInterface
CreateViewController *-- MultiplayerGame
CreateViewController *-- GameServer

ClientInterface *-- PlayerClient
ClientInterface o-- Actions
GameServer o-- Actions
PlayerClient o-- Actions

GameServer *-- PlayerOnServer

Stone +-- StoneType

class SupertetrisApp {
    main()
}

abstract class ViewController {
}
note right: base class for all \n *ViewController classes

abstract class BoardListener {
    onGameover()
    onRowDeleted(int count)
    onRowAdded()
    onNext(Stone stone)
    onDropped()
    onMove()
    onRotate()
    onSpawn(Stone stone)
}

class StartViewController {
}

class BoardViewController {
    gameController : GameController
}

class MultiBoardViewController {
}

class GameController {
    board : Board
    start()
    stop()
}

class OpponentBoard {
}

class ClientInterface {
}

interface Actions {
}

class Board {
    currentStone : Stone
    nextStone : Stone
    matrix : int[][]
    downTimer : Timeline
}

class Stone {
    matrix : int[][]
    stoneType : StoneType
}

class StoneType {
    color : Color
    matrix : int[][]
}

class Scores {
    level : int
    points : int
    lineCount : int
}



@enduml