@startuml
skinparam classAttributeIconSize 0


SupertetrisApp "1" *-- "1" StartViewController
SupertetrisApp "1" *-- "1" BoardViewController
StartViewController "1" *-- "1" BoardViewController
BoardViewController "1" *-- "1" GameController
GameController "1" *-- "1" Board
Board "1" *-- "1" Stones
Stones "1" *-- "*" Stone
Timer "1" -- "1" GameController
Player "1-2" -- "1" GameController
Score "1" -- "1" GameController
MultiplayerViewController -- GameController
MultiplayerViewController -- StartViewController
ViewController -- MultiplayerViewController
ViewController -- StartViewController
ViewController -- BoardViewController
TetrisServer -- TetrisClient
TetrisServer "1" -- "1" TetrisServerThread
TetrisServer "1" -- "1" GameController

class SupertetrisApp {
    void maim()
}

abstract class ViewController {
}

class StartViewController {
    public void btnSingleplayerClick()
    public void btnMultiplayerClick()
}

class BoardViewController {
    gameController : GameController
}

class MultiplayerViewController {

}

class GameController {
    board : Board
    start()
    stop()
}

class Board {
    stones: Stone[]
}

class Stones {

}

class Stone {

}

class Player {
    String name
}

class Timer {
}

class Score {
    int level
    int points
    int rows
}

class TetrisClient {

}

class TetrisServer {
}

class TetrisServerThread {
}


@enduml