@startuml
skinparam classAttributeIconSize 0

SupertetrisApp ..> StartViewController
StartViewController ..> BoardViewController
StartViewController ..> LobbyViewController
BoardViewController "1" *--* "1" GameController
GameController "1" *-- "1" Board
GameController "1" *-- "1" Stopwatch
GameController "1" *-- "1" Scores
BoardListener <-- Board
Board "1" *-- "*" Stone
GameController <-- MultiGameController
Board <-- MultiplayerBoard
BoardViewController ..> GameoverViewController
MultiBoardViewController ..> GameoverViewController
MultiBoardViewController *-- MultiGameController
MultiGameController *-- OpponentBoard
MultiplayerGame ..> MultiBoardViewController

ViewController <-- StartViewController
ViewController <-- BoardViewController
ViewController <-- MultiBoardViewController
ViewController <-- LobbyViewController
ViewController <-- GameoverViewController

ViewController *-- GameServer
ViewController *-- PlayerClient
ViewController *-- ClientInterface
ViewController *--* MultiplayerGame

ClientInterface *-- PlayerClient
ClientInterface o-- Actions
GameServer o-- Actions
PlayerClient o-- Actions

GameServer *-- PlayerOnServer

class SupertetrisApp {
    void main()
}

abstract class ViewController {
}

abstract class BoardListener {
}

class StartViewController {
    public void btnSingleplayerClick()
    public void btnMultiplayerClick()
}

class BoardViewController {
    gameController : GameController
}

class MultiBoardViewController {
}

class GameController {
    board : Board
    start()
    stop()
}

class OpponentBoard {
}

class ClientInterface {
}

interface Actions {
}

class Board {
    stones: Stone[]
}

class Stone {
}

class Scores {
    int level
    int points
    int rows
}

@enduml